# Generated by Django 2.0.2 on 2018-11-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='boton',
            field=models.CharField(max_length=100, null=True, verbose_name='boton'),
        ),
    ]
