# Generated by Django 2.0.2 on 2018-11-03 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_remove_about_boton'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About',
            new_name='Post',
        ),
    ]
